blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/gabecmelo/Studdup/discussions
    about: For questions and general discussion (not bug reports).
